"""
Stage 8 — Generate final committee-reviewed phenotyping report.

Reads all stage outputs and produces:
- docs/phenotyping/06_stage5_results.md
- docs/phenotyping/07_stage6_validation.md  (combines stability + cluster profiles)
- docs/phenotyping/08_stage7_outcomes.md
- docs/phenotyping/09_FINAL_REPORT.md (single committee-reviewed manuscript-ready doc)
"""

import pandas as pd
import json
from pathlib import Path

OUT = Path('/home/user/dialysis/outputs/phenotyping')
DOC = Path('/home/user/dialysis/docs/phenotyping')

# Load everything
quality = pd.read_csv(OUT / 'stage5_cluster_quality_metrics.csv')
ari = pd.read_csv(OUT / 'stage5_cross_algorithm_ARI.csv')
desc = pd.read_csv(OUT / 'stage6_cluster_descriptions.csv')
imp_audit = pd.read_csv(OUT / 'stage6_cluster_imputation_audit.csv')
outcomes = pd.read_csv(OUT / 'stage7_outcomes_by_phenotype.csv')
stats = pd.read_csv(OUT / 'stage7_outcome_chi2_logrank.csv')

with open(OUT / 'stage5_chosen_solution_metadata.json') as f:
    meta = json.load(f)

# ----------------------------------------------------------------
# Stage 5 results doc
# ----------------------------------------------------------------

stage5_md = f"""# Stage 5 — Clustering Execution Results

**Date:** generated by Stage 8 report script

## Locked protocol (DEC-PHENO-006) was applied without modification.

## Quality metrics across all (algorithm, K)

{quality.to_markdown(index=False, floatfmt='.3f')}

## Cross-algorithm Adjusted Rand Index

{ari.to_markdown(index=False, floatfmt='.3f')}

## Chosen solution per locked criteria

- **Algorithm:** {meta['algorithm']}
- **K:** {meta['K']}
- **Silhouette:** {meta['silhouette']:.3f}
- **Mean stability:** {meta['mean_stability']:.3f}
- **Min cluster size:** {meta['min_cluster_size']}
- **Cross-algorithm consensus:** {meta['consensus_status']}

## Cross-algorithm ARI at chosen K

{json.dumps(meta['cross_algo_ARI'], indent=2)}
"""

with open(DOC / '06_stage5_results.md', 'w') as f:
    f.write(stage5_md)

# ----------------------------------------------------------------
# Stage 6 validation
# ----------------------------------------------------------------

stage6_md = f"""# Stage 6 — Phenotype Validation

## Cluster profiles (means for continuous, % for binary)

{desc.to_markdown(index=False, floatfmt='.2f')}

## Imputation rate per cluster

If a single cluster has substantially higher imputation than others (>2x), it suggests that cluster is partly defined by missing-data patterns rather than biology.

{imp_audit.pivot(index='variable', columns='phenotype', values='pct_imputed').to_markdown(floatfmt='.1f')}
"""

with open(DOC / '07_stage6_validation.md', 'w') as f:
    f.write(stage6_md)

# ----------------------------------------------------------------
# Stage 7 outcomes
# ----------------------------------------------------------------

stage7_md = f"""# Stage 7 — Outcome Linkage (DESCRIPTIVE)

⚠️ **All p-values below are descriptive only.** Outcomes were never inputs to clustering. These tests characterize phenotypes, they do not establish inferential validity.

## Combined outcome table by phenotype

{outcomes.to_markdown(index=False, floatfmt='.2f')}

## Descriptive test statistics

{stats.to_markdown(index=False, floatfmt='.4g')}

## Caveats

- Outcomes were not used to define phenotypes (Rule 2)
- p-values shown above are not corrected for multiplicity
- Phenotype-outcome inference would require a separate, pre-registered analysis using these phenotypes as a fixed grouping variable
"""

with open(DOC / '08_stage7_outcomes.md', 'w') as f:
    f.write(stage7_md)

# ----------------------------------------------------------------
# FINAL REPORT
# ----------------------------------------------------------------

final = f"""# Phenotyping of HF Patients Initiating Dialysis — Final Report

**Project:** Phenotype identification using locked-protocol clustering
**Committee deliberation:** Per `00_CHARTER.md`
**Decision log:** `02_DECISION_LOG.md`

## Executive Summary

A pre-registered phenotyping analysis was performed on n={int(desc['n'].sum())} heart failure patients initiating dialysis. The analysis used 18 clinical and echocardiographic variables, 3 clustering algorithms (K-means, Ward, GMM), and pre-specified selection criteria. The chosen solution is **{meta['algorithm']}** with **K={meta['K']}** clusters, with **{meta['consensus_status'].lower()}** across algorithms.

## Methods

### Data preprocessing
- **Source:** raw `base_analysis_dataset.xlsx`
- **N retained:** {int(desc['n'].sum())} of 645 (dropped {645 - int(desc['n'].sum())} with missing low-missingness variables)
- **Variables:** 18 (12 continuous, 6 binary) covering demographics, comorbidity, cardiac structure/function, hemodynamics, and labs
- **Imputation:** kNN(k=5) for 6 variables with 5-25% missingness
- **Excluded:** 4 variables with >25% missingness (LV wall thickness, AorticValveStructure, Tissue Doppler S-velocity septal, sbp)
- **Scaling:** z-score for continuous; binary unscaled

### Clustering protocol (locked before execution)
- 3 algorithms × 5 K values (2-6) = 15 solutions
- Selection: multi-criterion ranking (silhouette, Calinski-Harabasz, Davies-Bouldin, bootstrap stability)
- Hard floor: minimum cluster n=30
- Cross-algorithm consensus required (ARI ≥0.5)

## Results

### Phenotype profiles

{desc[['phenotype','n']].to_markdown(index=False)}

See `07_stage6_validation.md` for complete profiles.

### Outcomes by phenotype (descriptive)

{outcomes[['phenotype','n','deaths_1yr','pct_dead_1yr','median_survival_days','mean_hosp_total']].to_markdown(index=False, floatfmt='.1f')}

### Validation status

| Criterion | Result |
|---|---|
| Min cluster size ≥ 30 | {meta['min_cluster_size']} |
| Mean stability | {meta['mean_stability']:.3f} |
| Cross-algorithm consensus | {meta['consensus_status']} |
| Clinical interpretability | requires manual CARD/NEPH review |

## Limitations

1. **Sample size** (n=602) is modest for clustering; phenotype counts smaller than 50 should be interpreted cautiously.
2. **Imputation** (kNN, k=5) may pull imputed patients toward neighbors; cluster assignments for high-imputation variables should be reviewed.
3. **Cross-sectional** — phenotypes describe baseline state; trajectory analysis would require longitudinal echo data.
4. **Single center** — external validation needed before generalization.
5. **Outcome separation is descriptive only** — phenotypes were not built to predict outcomes.

## Recommendations

1. Manual review by cardiologist and nephrologist of cluster profiles for clinical face validity.
2. Comparison to literature phenotypes (e.g., Shah HFpEF phenomapping) for nomenclature alignment.
3. If face-valid, plan pre-registered phenotype-outcome analysis as a separate study.
4. Consider external validation cohort.

## Decision audit trail

All decisions documented in `02_DECISION_LOG.md` (DEC-PHENO-001 through DEC-PHENO-006). The decision log can be appended to a manuscript supplement to demonstrate methodological rigor.
"""

with open(DOC / '09_FINAL_REPORT.md', 'w') as f:
    f.write(final)

print(f'Final report saved: {DOC / "09_FINAL_REPORT.md"}')
print('\n=== STAGE 8 DONE ===')
